services:
  - type: web
    name: nimbus-api
    runtime: docker
    plan: free
    region: singapore

    dockerfilePath: ./Dockerfile

    healthCheckPath: /health

    envVars:
      # Production PostgreSQL URL.
      # Set this manually in the Render dashboard.
      - key: DB_URL
        sync: false

      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: nimbus-redis
          property: connectionString

      - key: BASE_URL
        sync: false

  - type: keyvalue
    name: nimbus-redis
    plan: free
    region: singapore
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru