apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimbus-api
  template:
    metadata:
      labels:
        app: nimbus-api
    spec:
      containers:
        - name: api
          image: nimbus-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: nimbus-config
                  key: DB_URI

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nimbus-config
                  key: REDIS_HOST

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nimbus-secret
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: nimbus-api
spec:
  selector:
    app: nimbus-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP