apiVersion: v1
kind: ConfigMap
metadata:
  name: nimbus-migrations
data:
  000001_create_codes.up.sql: |
    CREATE TABLE IF NOT EXISTS codes (
        id SERIAL PRIMARY KEY,
        short_code VARCHAR(6) UNIQUE NOT NULL,
        original_url TEXT NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );

  000002_create_clicks.up.sql: |
    CREATE TABLE IF NOT EXISTS clicks (
        id SERIAL PRIMARY KEY,
        code_id INTEGER NOT NULL REFERENCES codes(id),
        clicked_at TIMESTAMP NOT NULL DEFAULT NOW(),
        reference TEXT
    );

---
apiVersion: batch/v1
kind: Job
metadata:
  name: nimbus-migrations
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: nimbus-migrations
    spec:
      restartPolicy: OnFailure

      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -U nimbus -d nimbus; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done

      containers:
        - name: migrate
          image: postgres:16-alpine
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: nimbus-secret
                  key: DB_PASSWORD

          command:
            - sh
            - -c
            - |
              psql \
                -h postgres \
                -U nimbus \
                -d nimbus \
                -f /migrations/000001_create_codes.up.sql

              psql \
                -h postgres \
                -U nimbus \
                -d nimbus \
                -f /migrations/000002_create_clicks.up.sql

          volumeMounts:
            - name: migrations
              mountPath: /migrations

      volumes:
        - name: migrations
          configMap:
            name: nimbus-migrations